Feat/create basic info screen
kookmin-sw/capstone-2024-18 pull request #19
Opened 2024-04-12 06:28 UTC by nanana3679

## 연관된 이슈

#15 #16 

## 파트
- FE

## 작업 내용
- 기본 정보 입력 페이지 구현 및 API 연동
- 루트 페이지 구현 및 자동 페이지 전환 구현
  - 앱 실행 시 루트 페이지 진입 
  - 로그인 정보가 있고 기본 정보가 있을 경우 자동 로그인
  - 로그인 정보가 있고 기본 정보가 없을 경우 기본 정보 입력 페이지로 이동
  - 로그인 정보가 없을 경우 로그인 페이지로 이동
- 자세한 구현 사항은 #15 #16 이슈 참고

## 리뷰 요청사항
- 새로 작성된 컴포넌트 확인 바랍니다.
  - CustomProgressBar
  - CustomSlider
  - Title

2024-04-12 07:09 UTC, gee2450 commented
Title component 이름을 바꿔야할 것 같습니다!

2024-04-13 08:42 UTC, gee2450 commented
음... material io에서 저희 서비스와 비슷한 느낌의 component의 이름은 top bar인 것 같은데 이 이름은 어떠실까요? 사실 뭔가 더 좋을 것 같은 이름이 있을 것 같은데 모르겠습니다.. 하하
https://m2.material.io/components/app-bars-top#usage

2024-04-13 08:46 UTC, gee2450 reviewed
Title 컴포넌트의 이름 제외 다른 것들 다 확인했습니다.

2024-04-13 08:49 UTC, gee2450 requested changes
확인했습니다! 이걸 보내야 머지 가능하게 되나..?

2024-04-13 08:51 UTC, gee2450 approved these changes
뭔데 이건가 진짜. Title component 이름 제외 다 확인했습니다.

2024-04-15 07:10 UTC, nanana3679 commented
@gee2450 혹시 HeaderBar는 어떤가요?

2024-04-20 09:09 UTC, merged